package NewsBufferApp;


/**
* NewsBufferApp/_NewsBufferImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/anass/workspaces/my-soccer-project/news-service/src/main/idl/NewsBuffer.idl
* Wednesday, May 13, 2026 4:37:51 PM CEST
*/

public abstract class _NewsBufferImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements NewsBufferApp.NewsBuffer, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _NewsBufferImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("put", new java.lang.Integer (0));
    _methods.put ("getById", new java.lang.Integer (1));
    _methods.put ("getAll", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // NewsBufferApp/NewsBuffer/put
       {
         String newsXML = in.read_string ();
         boolean $result = false;
         $result = this.put (newsXML);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // NewsBufferApp/NewsBuffer/getById
       {
         int idNews = in.read_long ();
         org.omg.CORBA.StringHolder newsXML = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.getById (idNews, newsXML);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (newsXML.value);
         break;
       }

       case 2:  // NewsBufferApp/NewsBuffer/getAll
       {
         org.omg.CORBA.StringHolder allNewsXML = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.getAll (allNewsXML);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (allNewsXML.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NewsBufferApp/NewsBuffer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _NewsBufferImplBase
