services:
  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
    networks:
      - my-soccer-network

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - my-soccer-network

  players-service:
    image: players-service:0.0.1-SNAPSHOT
    container_name: players-service
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/my_soccer_project
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - EUREKA_INSTANCE_HOSTNAME=players-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    networks:
      - my-soccer-network

  comments-service:
    image: comments-service:0.0.1-SNAPSHOT
    container_name: comments-service
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/my_soccer_project
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - EUREKA_INSTANCE_HOSTNAME=comments-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    networks:
      - my-soccer-network

  ideal-team-service:
    image: ideal-team-service:0.0.1-SNAPSHOT
    container_name: ideal-team-service
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/my_soccer_project
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - EUREKA_INSTANCE_HOSTNAME=ideal-team-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
    networks:
      - my-soccer-network

  postgres:
    image: postgres:18.3-alpine3.23
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_soccer_project
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my-soccer-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - my-soccer-network

networks:
  my-soccer-network:
    driver: bridge

volumes:
  postgres_data:

