services:
  config-server:
    image: config-server:0.0.1-SNAPSHOT
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/aek676/spring-my-soccer-project-microservices-config.git
    networks:
      - my-soccer-network

  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: local
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
    depends_on:
      - config-server
    networks:
      - my-soccer-network

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      EUREKA_INSTANCE_HOSTNAME: gateway
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
    depends_on:
      - config-server
      - eureka-server
    networks:
      - my-soccer-network

  players-service:
    image: players-service:0.0.1-SNAPSHOT
    container_name: players-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      EUREKA_INSTANCE_HOSTNAME: players-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
    depends_on:
      - config-server
      - eureka-server
      - postgres
    networks:
      - my-soccer-network

  comments-service:
    image: comments-service:0.0.1-SNAPSHOT
    container_name: comments-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      EUREKA_INSTANCE_HOSTNAME: comments-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
    depends_on:
      - config-server
      - eureka-server
      - postgres
    networks:
      - my-soccer-network

  ideal-team-service:
    image: ideal-team-service:0.0.1-SNAPSHOT
    container_name: ideal-team-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      EUREKA_INSTANCE_HOSTNAME: ideal-team-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888/
    depends_on:
      - config-server
      - eureka-server
      - postgres
    networks:
      - my-soccer-network

  bun-backend:
    build: ./bun-backend
    container_name: bun-backend
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_COMPONENT_URI: http://config-server:8888
      NODE_ENV: local
    depends_on:
      - mongo
      - eureka-server
    networks:
      - my-soccer-network

  postgres:
    image: postgres:18.3-alpine3.23
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-soccer-project
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my-soccer-network

  mongo:
    image: mongo:4.4.18
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - my-soccer-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo
    networks:
      - my-soccer-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - my-soccer-network

networks:
  my-soccer-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
