package NewsBufferApp;


/**
* NewsBufferApp/NewsBuffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/anass/workspaces/my-soccer-project/news-service/src/main/idl/NewsBuffer.idl
* Wednesday, May 13, 2026 4:37:51 PM CEST
*/

public interface NewsBuffer extends NewsBufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NewsBuffer
