package NewsBufferApp;


/**
* NewsBufferApp/NewsBufferHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/anass/workspaces/my-soccer-project/news-service/src/main/idl/NewsBuffer.idl
* Wednesday, May 13, 2026 5:30:59 PM CEST
*/

abstract public class NewsBufferHelper
{
  private static String  _id = "IDL:NewsBufferApp/NewsBuffer:1.0";

  public static void insert (org.omg.CORBA.Any a, NewsBufferApp.NewsBuffer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NewsBufferApp.NewsBuffer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NewsBufferApp.NewsBufferHelper.id (), "NewsBuffer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NewsBufferApp.NewsBuffer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NewsBufferStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NewsBufferApp.NewsBuffer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static NewsBufferApp.NewsBuffer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NewsBufferApp.NewsBuffer)
      return (NewsBufferApp.NewsBuffer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NewsBufferApp._NewsBufferStub stub = new NewsBufferApp._NewsBufferStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static NewsBufferApp.NewsBuffer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NewsBufferApp.NewsBuffer)
      return (NewsBufferApp.NewsBuffer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NewsBufferApp._NewsBufferStub stub = new NewsBufferApp._NewsBufferStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
