package NewsBufferApp;


/**
* NewsBufferApp/NewsBufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/anass/workspaces/my-soccer-project/news-service/src/main/idl/NewsBuffer.idl
* Wednesday, May 13, 2026 4:30:44 PM CEST
*/

public interface NewsBufferOperations 
{
  boolean put (String newsXML);
  boolean getById (int idNews, org.omg.CORBA.StringHolder newsXML);
  boolean getAll (org.omg.CORBA.StringHolder allNewsXML);
  boolean isEmpty ();
  int getCount ();
} // interface NewsBufferOperations
