/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlayerDetail {
        "playerId": string;
    }
    interface PlayerList {
    }
}
declare global {
    interface HTMLPlayerDetailElement extends Components.PlayerDetail, HTMLStencilElement {
    }
    var HTMLPlayerDetailElement: {
        prototype: HTMLPlayerDetailElement;
        new (): HTMLPlayerDetailElement;
    };
    interface HTMLPlayerListElement extends Components.PlayerList, HTMLStencilElement {
    }
    var HTMLPlayerListElement: {
        prototype: HTMLPlayerListElement;
        new (): HTMLPlayerListElement;
    };
    interface HTMLElementTagNameMap {
        "player-detail": HTMLPlayerDetailElement;
        "player-list": HTMLPlayerListElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface PlayerDetail {
        "playerId": string;
    }
    interface PlayerList {
    }

    interface PlayerDetailAttributes {
        "playerId": string;
    }

    interface IntrinsicElements {
        "player-detail": Omit<PlayerDetail, keyof PlayerDetailAttributes> & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes]?: PlayerDetail[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `attr:${K}`]?: PlayerDetailAttributes[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `prop:${K}`]?: PlayerDetail[K] } & OneOf<"playerId", PlayerDetail["playerId"], PlayerDetailAttributes["playerId"]>;
        "player-list": PlayerList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "player-detail": LocalJSX.IntrinsicElements["player-detail"] & JSXBase.HTMLAttributes<HTMLPlayerDetailElement>;
            "player-list": LocalJSX.IntrinsicElements["player-list"] & JSXBase.HTMLAttributes<HTMLPlayerListElement>;
        }
    }
}
