CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    age INTEGER,
    birthdate DATE,
    nationality VARCHAR(255),
    height VARCHAR(255),
    weight VARCHAR(255),
    number INTEGER,
    team VARCHAR(255),
    league VARCHAR(255),
    position VARCHAR(255),
    photo VARCHAR(255),
    location JSONB,
    created TIMESTAMP(6)
);

INSERT INTO players (name, position, number, age, photo, location, created)
VALUES
  ('Vinícius Júnior', 'Forward', 7, 23,
   'https://i.pravatar.cc/64?img=14',
   '{"type": "Point", "coordinates": [-3.7038, 40.4168]}'::jsonb,
   NOW()),
  ('Lamine Yamal', 'Winger', 19, 17,
   'https://i.pravatar.cc/64?img=15',
   '{"type": "Point", "coordinates": [2.1686, 41.3874]}'::jsonb,
   NOW()),
  ('Kylian Mbappé', 'Forward', 9, 25,
   NULL,
   '{"type": "Point", "coordinates": [2.3522, 48.8566]}'::jsonb,
   NOW()),
  ('Federico Valverde', 'Midfielder', 8, 25,
   'https://i.pravatar.cc/64?img=16',
   '{"type": "Point", "coordinates": [-3.7038, 40.4168]}'::jsonb,
   NOW());
