db = db.getSiblingDB("my-soccer-project");

db.createCollection("players");

db.players.insertMany([
	{
		_id: "1",
		name: "Marcus Rashford",
		firstName: "Marcus",
		lastName: "Rashford",
		age: 26,
		birthdate: new Date("1997-10-31"),
		nationality: "England",
		height: "1.80m",
		weight: "70kg",
		number: 10,
		team: "Manchester United",
		league: "Premier League",
		position: "Forward",
		photo: "https://i.pravatar.cc/64?img=11",
		location: {
			type: "Point",
			coordinates: [-2.2426, 53.4808],
		},
		created: new Date(),
	},
	{
		_id: "2",
		name: "Jude Bellingham",
		firstName: "Jude",
		lastName: "Bellingham",
		age: 20,
		birthdate: new Date("2003-06-29"),
		nationality: "England",
		height: "1.86m",
		weight: "75kg",
		number: 5,
		team: "Real Madrid",
		league: "La Liga",
		position: "Midfielder",
		location: {
			type: "Point",
			coordinates: [-3.7038, 40.4168],
		},
		created: new Date(),
	},
	{
		_id: "3",
		name: "Bukayo Saka",
		firstName: "Bukayo",
		lastName: "Saka",
		age: 22,
		birthdate: new Date("2001-09-05"),
		nationality: "England",
		height: "1.78m",
		weight: "65kg",
		number: 7,
		team: "Arsenal",
		league: "Premier League",
		position: "Winger",
		photo: "https://i.pravatar.cc/64?img=12",
		location: {
			type: "Point",
			coordinates: [-0.1278, 51.5074],
		},
		created: new Date(),
	},
	{
		_id: "4",
		name: "Declan Rice",
		firstName: "Declan",
		lastName: "Rice",
		age: 25,
		birthdate: new Date("1999-01-14"),
		nationality: "England",
		height: "1.85m",
		weight: "80kg",
		number: 41,
		team: "Arsenal",
		league: "Premier League",
		position: "Defensive Midfielder",
		photo: "https://i.pravatar.cc/64?img=13",
		location: {
			type: "Point",
			coordinates: [-0.1278, 51.5074],
		},
		created: new Date(),
	},
]);
