module NewsBufferApp {
    interface NewsBuffer {
        boolean put(in string newsXML);
        boolean getById(in long idNews, out string newsXML);
        boolean getAll(out string allNewsXML);
    };
};