name: Main CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write
  pull-requests: write
  checks: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      players: ${{ steps.filter.outputs.players }}
      comments: ${{ steps.filter.outputs.comments }}
      eureka: ${{ steps.filter.outputs.eureka }}
      gateway: ${{ steps.filter.outputs.gateway }}
      ideal_team: ${{ steps.filter.outputs.ideal_team }}
      bun_backend: ${{ steps.filter.outputs.bun_backend }}
      news_service: ${{ steps.filter.outputs.news_service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check changes
        uses: dorny/paths-filter@v4.0.1
        id: filter
        with:
          filters: |
            players:
              - 'players-service/**'
            comments:
              - 'comments-service/**'
            gateway:
              - 'gateway/**'
            ideal_team:
              - 'ideal-team-service/**'
            bun_backend:
              - 'bun-backend/**'
            news_service:
              - 'news-service/**'

  players:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.players == 'true' }}
    uses: ./.github/workflows/tmpl-java-maven-build-push-deploy.yml
    with:
      working_directory: "players-service"
      image_name: "players-service"
      push: ${{ github.event_name == 'push' }}
    secrets: inherit

  comments:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.comments == 'true' }}
    uses: ./.github/workflows/tmpl-java-maven-build-push-deploy.yml
    with:
      working_directory: "comments-service"
      image_name: "comments-service"
      push: ${{ github.event_name == 'push' }}
    secrets: inherit

  gateway:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.gateway == 'true' }}
    uses: ./.github/workflows/tmpl-java-maven-build-push-deploy.yml
    with:
      working_directory: "gateway"
      image_name: "api-gateway"
      push: ${{ github.event_name == 'push' }}
    secrets: inherit

  ideal-team:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ideal_team == 'true' }}
    uses: ./.github/workflows/tmpl-java-maven-build-push-deploy.yml
    with:
      working_directory: "ideal-team-service"
      image_name: "ideal-team-service"
      push: ${{ github.event_name == 'push' }}
    secrets: inherit

  bun-backend:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.bun_backend == 'true' }}
    uses: ./.github/workflows/bun-backend.yml
    with:
      push: ${{ github.event_name == 'push' }}
    secrets: inherit

  news-service:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.news_service == 'true' }}
    uses: ./.github/workflows/news-service.yml
    with:
      push: ${{ github.event_name == 'push' }}
    secrets: inherit
